### ISSUE TITLE
Delete a blob file do not work

### ISSUE THREAD

**Issue by Toutatis64** [iterative/dvc-azure#46]
When we do a dvc gc with -c argument, the file is expected to be cleaned on the cloud. 
However, the remove on dvc_azure.AzureFileSystem seems do not work, only removes the file locally ?!

**Comment by efiop** [comment]
@Toutatis64 Could you elaborate, please? Not seeing anything obvious in adlfs or our wrapper that could result in local file deletion.

**Comment by Toutatis64** [comment]
Well sorry, i'm able to see that there are requests on API delete blob from Azure portal, so it's probably another issue ... 
I close this one, i'll continue to investigate then.

**Comment by Toutatis64** [comment]
Was due to retention policies of 7 days :/ Not clear on the interface, but debugging specific file, I realized that the file appear in deleted blobs ! Sorry for the lost time.
