### ISSUE TITLE
Pin DVC version

### ISSUE THREAD

**Issue by domirohner** [iterative/dvc-azure#52]
Since the dvc version in dvc-azure isn't pinned, it is possible that you are using  a diffrent version of dvc even if you have pinned the dvc-azure version.
This may leads to issues with using dvc.

For example: The dvc version 3.* is available now. With this version there are some extra fileds added to the config which an older dvc version can't handle and run into errors. We used dvc-azure in a new Python environement with dvc version 3.* , pushed the data in the storage account and tried to download the data in another Python environment. Both environments had pinned the same version of dvc-azure, but since the second environment was created earlier, it still used dvc 2.* and can't handle the new fields.

**Comment by efiop** [comment]
@domirohner `dvc-azure` is not meant to be installed separately. Please use `pip install dvc[azure]` instead.
