### ISSUE TITLE
Version 3.1.0 not available on conda-forge

### ISSUE THREAD

**Issue by kutkopy** [iterative/dvc-azure#99]
The newest release of dvc-azure (3.1.0) is currently not available on conda-forge:
https://anaconda.org/conda-forge/dvc-azure/files

**Comment by shcheklein** [comment]
@kutkopy thanks. I'm looking into this.

**Comment by shcheklein** [comment]
@kutkopy should be fixed https://github.com/conda-forge/dvc-azure-feedstock/pull/20 . please confirm. Thanks for the report.
